title: Critical Digital Practices
description: Course development sandbox
theme: just-the-docs

url: https://cdl-geneseo.github.io/critical-digital-practices

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
